export const SET_REMINDERS = 'REMINDERS/SET_REMINDERS';

export const ADD_REMINDER = 'REMINDERS/ADD_REMINDER';

export const DELETE_REMINDER = 'REMINDERS/DELETE_REMINDER';

export const COMPLETE_REMINDER = 'REMINDERS/COMPLETE_REMINDER';

export const UNCOMPLETE_REMINDER = 'REMINDERS/UNCOMPLETE_REMINDER';
