export const GET_TODOS = 'TODOS/GET_TODOS';

export const ADD_TODO = 'TODO/ADD_TODO';

export const COMPLETE_TODO = 'TODO/COMPLETE_TODO';

export const UNCOMPLETE_REMINDER = 'TODO/UNCOMPLETE_REMINDER';
